### ISSUE TITLE
New Wikivoyage crashes

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#282]
Useres reports that the new (released yesterday) Wikivoyage app by searching:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.kiwix.kiwixcustomwikivoyage/org.kiwix.kiwixcustomwikivoyage.SearchActivity}: android.database.sqlite.SQLiteException: no such column: recentSearches.searchString (code 1): , while compiling: SELECT DISTINCT recentSearches.searchString AS searchString FROM recentSearches ORDER BY recentSearches._id DESC LIMIT 5
#################################################################
Error Code : 1 (SQLITE_ERROR)
Caused By : SQL(query) error or missing database.
    (no such column: recentSearches.searchString (code 1): , while compiling: SELECT DISTINCT recentSearches.searchString AS searchString FROM recentSearches ORDER BY recentSearches._id DESC LIMIT 5)
#################################################################
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3253)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
    at android.app.ActivityThread.access$1100(ActivityThread.java:221)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:158)
    at android.app.ActivityThread.main(ActivityThread.java:7224)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: android.database.sqlite.SQLiteException: no such column: recentSearches.searchString (code 1): , while compiling: SELECT DISTINCT recentSearches.searchString AS searchString FROM recentSearches ORDER BY recentSearches._id DESC LIMIT 5
#################################################################
Error Code : 1 (SQLITE_ERROR)
Caused By : SQL(query) error or missing database.
    (no such column: recentSearches.searchString (code 1): , while compiling: SELECT DISTINCT recentSearches.searchString AS searchString FROM recentSearches ORDER BY recentSearches._id DESC LIMIT 5)
#################################################################
    at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
    at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1058)
    at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:623)
    at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
    at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
    at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
    at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
    at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1454)
    at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1429)
    at com.yahoo.squidb.data.adapter.SQLiteDatabaseAdapter.rawQuery(SQLiteDatabaseAdapter.java:209)
    at com.yahoo.squidb.data.SquidDatabase.rawQuery(SquidDatabase.java:570)
    at com.yahoo.squidb.data.SquidDatabase.query(SquidDatabase.java:1379)
    at org.kiwix.kiwixcustomwikivoyage.database.RecentSearchDao.getRecentSearches(RecentSearchDao.java:27)
    at org.kiwix.kiwixcustomwikivoyage.SearchActivity.onCreate(SearchActivity.java:53)
    at android.app.Activity.performCreate(Activity.java:6876)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
    ... 9 more
```

**Comment by mhutti1** [comment]
@kelson42 Clearing app data should fix this for now. It looks like the app database isn't being upgraded correctly for some users.

**Comment by kelson42** [comment]
@mhutti1 anyway to do that programmatically? To avoid the problem to happen at all?

**Comment by mhutti1** [comment]
@kelson42 Well that would wipe the whole database. I mean you could though.

**Comment by kelson42** [comment]
@mhutti1 why are we not able to upgrade the database in a way it works? No way to assure "recentSearches.searchString" always exists?

**Comment by mhutti1** [comment]
@kelson42 It should have done so but with custom app releases at different points its possible a previous update was half way through a database upgrade I guess. I really can't see whats wrong.

**Comment by mhutti1** [comment]
@kelson42 The database class hasn't been touched in 14 days so versions 10,11 and 12 didn't have this issue I think?

**Comment by mhutti1** [comment]
@kelson42  I think what I just pushed should fix it but am not certain. I am away from my computer till Tuesday now though.

**Comment by kelson42** [comment]
@mhutti1 Impacted user seems happy after new release :) Well done.

**Comment by mhutti1** [comment]
I don't think this is fully fixed. I think I know what to do but might not be able to fix till late tomorrow.

**Comment by mhutti1** [comment]
@kelson42 I think I have fixed it now but can't access computer. Can you check it compiles and then push update please.

**Comment by kelson42** [comment]
Yes, You are right. We still get crashes. I have made a new release with your patch. THX. We will see how things evolve.

**Comment by kelson42** [comment]
Problem really fixed now. Thx @mhutti1
